name: Unit tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.9]
    env:
      NAMESPACE: '@plone-collective'
      GIT_NAME: volto-authomatic
      GIT_USER: 'collective'
      GIT_BRANCH: ${GITHUB_REF##*/}
    steps:
      - name: Main checkout
        uses: actions/checkout@v2

      # node setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # node install
      - name: Install dependencies
        run: yarn install

      - name: Install yo and @plone/generator-volto
        run: npm i -g yo @plone/generator-volto

      - name: Setup addon testing environment
        run: npx -p @plone/scripts addon clone https://github.com/${{env.GIT_USER}}/${{env.GIT_NAME}}.git --branch ${{env.GIT_BRANCH}}

      # Unit tests
      - name: Unit tests
        run: cd addon-testing-project && yarn && CI=true yarn test
